#Random tools I normally use

#Adding taps (repos) on top
tap "homebrew/bundle"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "homebrew/cask-fonts"

brew "expect"
brew "mtr"
#I use smartmontools to monitor disk health
brew "smartmontools"
brew "tcptraceroute"
brew "telnet"
cask "beardedspice"
cask "betterdisplay"
cask "google-cloud-sdk"
cask "google-drive"
cask "microsoft-remote-desktop"
cask "raycast"
cask "setapp"
cask "obs"

#This errored out, I prefer to install it from the yabai script
#brew "koekeishiya/formulae/yabai"

#Will install wineskin later on when needed, it errors out if part of my script
#cask "wineskin"
#gstreamer-runtime or gstreamer.framework is installed by
#gcenx/wine/wineskin
