foreground            #d8ffd8
background            #000000
selection_foreground  #d8ffd8
selection_background   #ffe680
url_color             #66ff99
# black
color0                #000000
color8                #ffe07a
# red
color1                #c96d00
color9                #c96d00
# green
color2                #ff9d00
color10               #ff9d00
# yellow
color3                #98ff98
color11               #98ff98
# blue
color4                #00e65c
color12               #00e65c
# magenta
color5                #ffc94a
color13               #ffc94a
# cyan
color6                #66ff99
color14               #66ff99
# white
color7                #d8ffd8
color15               #d8ffd8
# Cursor colors
cursor                #00cc4f
cursor_text_color     #000000
# Tab bar colors
active_tab_foreground  #000000
active_tab_background   #ff9d00
inactive_tab_foreground #66ff99
inactive_tab_background #000000
# Marks
mark1_foreground      #000000
mark1_background      #c96d00
# Splits/Windows
active_border_color   #00e65c
inactive_border_color  #000000
