# Filename: ~/github/dotfiles-latest/.markdownlint.yaml
# ~/github/dotfiles-latest/.markdownlint.yaml
#
# https://github.com/DavidAnson/markdownlint
#
# Copy this file to each dir in which you want the settings to be applied, for
# example, I copied it to my 'github/obsidian_main' and
# 'github/linkarzu.github.io' dir.
# I copied it to '~/github' but the changes were never applied, so make sure you
# copy it to the working directory, you can see it with `:pwd`

# Unordered list style
# Disabled this because the TOC was giving me warnings for using other symbols
# than -
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md004.md
MD004: false

# Unordered list indentation
# I disable this because for some documents I use 4 space indenting, like
# markdown files that I need to upload to confluence
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md007.md
MD007: false

# Hard tabs
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md010.md
# This rule is triggered by any lines that contain hard tab characters instead
# of using spaces for indentation. To fix this, replace any hard tab characters
# with spaces instead
MD010:
  code_blocks: false

# Multiple consecutive blank lines
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md012.md
# Not sure why at the end of markdown files I get an error that there are 2
# blank lines when there's only 1, so increasing this to fix it
MD012:
  maximum: 2

# Line length
# I disabled this because autoformatting takes care of the line length for me,
# so it's not necessary, also if I have a really long markdown link with {:target="\_blank"}
# at the end, it will trigger it, and haven't looked into how to fix that
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md013.md
MD013: false
# MD013:
#   code_blocks: false
#   headings: false
#   tables: false

# Spaces after list markers
# Disabled this because of confluence formatting
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md030.md
MD030: false

# Inline HTML
# I disabled this so it doesn't warn me when I include HTML code in my markdown
# files, sometimes HTML is needed in github readmes
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md033.md
MD033:
  false
  # allowed_elements: ["a", "img", "div"]
