#!/bin/bash

# Filename: ~/github/dotfiles-latest/sketchybar/felixkratz/sketchybarrc

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh"  # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items"     # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

# Needs to have Regular, Bold, Semibold, Heavy and Black variants
# FONT="SF Pro"
# FONT="JetBrainsMono Nerd Font"
FONT="MesloLGM Nerd Font"

# All paddings use this value (icon, label, background), default is 3 but I
# decreased it
PADDINGS=1

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
(cd $CONFIG_DIR/helper && make)
$CONFIG_DIR/helper/helper $HELPER >/dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist >/dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
  height=45
  color=$BAR_COLOR
  border_width=2
  border_color=$BAR_BORDER_COLOR
  shadow=off
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  y_offset=-5
  margin=-2
  topmost=window
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=9
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=on
)

sketchybar --default "${defaults[@]}"

###############################################################################
#                                Left side
###############################################################################

# Shows the apple logo, you can change it's color in "items/apple.sh"
# If you click on it, you can see preferences, activity and lock screen
source "$ITEM_DIR/apple.sh"

# source "$ITEM_DIR/spaces.sh"

# I use yabai, but not sure what this does, I don't see a difference
# Not sure if related to "skhd shortcuts should trigger the sketchybar event" in
# the owner dotfiles
# source "$ITEM_DIR/yabai.sh"

# Shows the name and icon of the app currently focused
# Clicking it opens mission control (can be customized)
source "$ITEM_DIR/front_app.sh"

# Community plugin that I modified, so that it shows you the mic name
# If you right click it you can change the mic.
# Shows you the value of the input volume level
source "$ITEM_DIR/mic.sh"

###############################################################################
#                                 Center
###############################################################################

# Shows album art and song name, I prefer this as it give me useful info
# Disabled this as it always kept it in the middle even if nothing was playing
# source "$ITEM_DIR/media.sh"

# Shows floating window when spotify is playing a song
# source "$ITEM_DIR/spotify.sh"

###############################################################################
#                               Right side
###############################################################################

# If calendar is clicked, will run zen.sh which hides everything, but you can
# customize it to your liking
source "$ITEM_DIR/calendar.sh"

# Runs "brew outdated" command and shows you amount of outdated packages
# Will install an old package so you can see the number increase
# `brew install ~/Downloads/wezterm.rb`
# `https://github.com/wez/wezterm/releases`
# `brew update && brew upgrade` updates the package and clears the counter
# -----> Make sure to add the section to the .zshrc file, so that package count is
# updated automatically after running brew commands
# `https://github.com/linkarzu/dotfiles-latest/blob/8fd9af824fc1db73de185b3733dac5d8514f9fb0/zshrc/zshrc-file.sh#L225-L247`
source "$ITEM_DIR/brew.sh"

# DND not working with sonoma, will figure it out later (hopefully)
source "$ITEM_DIR/dnd.sh"

# Shows github notifications via gh cli, mine aren't working properly
# `gh api notifications` shows nothing but `gh status` does
source "$ITEM_DIR/github.sh"

# Shows the SSID you're connected to, and the IP address assigned
source "$ITEM_DIR/wifi.sh"

# By default the icon will only show when on battery and if it's 50% or less,
# you can change "plugins/battery.sh" if needed to modify the behavior
source "$ITEM_DIR/battery.sh"

# left click to change volume
# right click to switch audio sources, you need switchaudio-osx
source "$ITEM_DIR/volume.sh"

# CPU usage indicator
source "$ITEM_DIR/cpu.sh"

source "$ITEM_DIR/timer.sh"

###############################################################################
#                            Community plugins
###############################################################################

source "$ITEM_DIR/custom_text.sh"
source "$ITEM_DIR/notification.sh"

###############################################################################

sketchybar --hotload on

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
